server:
  port : 8088

  
spring : 
  ####  DB
  datasource : 
    driver-class-name : org.mariadb.jdbc.Driver
    url : jdbc:mariadb://localhost:3306//korea
    username : kj
    password : 123456
    
  ### 내용 갱신시 서버 reloading
  devtools : 
    livereload : 
      enabled : true
      
      
  ### view page
  mvc : 
    view : 
      prefix : /views/
      suffix : .jsp